name: VoxelMimic
main: com.thevoxelbox.voxelmimic.VoxelMimic
version: 1.43
website: http://voxelwiki.com
author: Gavjenks
description: >
             Gather a palette based on items in your vicinity.
commands:
  mimic:
    description: Matches your inventory to types of blocks around you
    usage: |
           /mimic [optional: radius]